//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPAccses.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subassemblies
    {
        public int ID_Subassemblies { get; set; }
        public string Name_Subassemblies { get; set; }
        public Nullable<int> Details { get; set; }
        public Nullable<int> Assemblyes { get; set; }
        public Nullable<int> Departament { get; set; }
    
        public virtual Assemblies Assemblies { get; set; }
        public virtual Department Department { get; set; }
        public virtual Detailes Detailes { get; set; }
        public virtual Detailes Detailes1 { get; set; }
    }
}
