//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MPAccses.MVVM.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasks
    {
        public int ID_Tasks { get; set; }
        public string Name_Task { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Departament { get; set; }
        public int Details { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Department Department1 { get; set; }
        public virtual Detailes Detailes { get; set; }
        public virtual Detailes Detailes1 { get; set; }
    }
}
